FROM alpine:3.13.2

RUN apk add \
    --update \
    --no-cache \
    openssh \
    rsync \
    && mkdir -m 0700 /root/.ssh

ADD ssh_config /root/.ssh/config
RUN chown root:root /root/.ssh/config \
    && chmod 0644 /root/.ssh/config

ADD entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["cat"]
